
computer=${computer}

computer.O11DW=CPU,GPU_E,GPU_J,NVME
# 5800X3D et 9070XT sur MSI B550
computer.O11DW.CPU.id=111
computer.O11DW.CPU.command=sensors k10temp-pci-00c3
computer.O11DW.CPU.sensor=Tctl:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.O11DW.GPU_E.id=110
computer.O11DW.GPU_E.command=sensors amdgpu-pci-2d00
computer.O11DW.GPU_E.sensor=edge:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.O11DW.GPU_J.id=114
computer.O11DW.GPU_J.command=sensors amdgpu-pci-2d00
computer.O11DW.GPU_J.sensor=junction:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.O11DW.NVME.id=112
computer.O11DW.NVME.command=sensors nvme-pci-0100
computer.O11DW.NVME.sensor=Composite:[^+]*\\+(\\d+\\.\\d+)\u00b0C

computer.MaxiMox=CPU,GPU_1,NVME_1,NVME_2,NVME_3,NVME_4,NIC
computer.MaxiMox.CPU.id=120
computer.MaxiMox.CPU.command=sensors coretemp-isa-0000
computer.MaxiMox.CPU.sensor=Package id 0:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.MaxiMox.GPU_1.id=121
computer.MaxiMox.GPU_1.command=sensors i915-pci-0300
computer.MaxiMox.GPU_1.sensor=temp1:[^+]*\\+(\\d+\\.\\d+)\u00b0C
# y a pas la temperature
computer.MaxiMox.GPU_2.id=122
computer.MaxiMox.GPU_2.command=sensors ucsi_source_psy_0_00081-i2c-0-08
computer.MaxiMox.GPU_2.sensor=temp1:[^+]*\\+(\\d+\\.\\d+)\u00b0C
# root@MaxiMox:~# lspci | grep memory
# 05:00.0 Non-Volatile memory controller: Kingston Technology Company, Inc. A2000 NVMe SSD [SM2263EN] (rev 03)
# 08:00.0 Non-Volatile memory controller: Realtek Semiconductor Co., Ltd. RTS5765DL NVMe SSD Controller (DRAM-less) (rev 01)
# 09:00.0 Non-Volatile memory controller: Realtek Semiconductor Co., Ltd. RTS5765DL NVMe SSD Controller (DRAM-less) (rev 01)
# 0a:00.0 Non-Volatile memory controller: Realtek Semiconductor Co., Ltd. RTS5765DL NVMe SSD Controller (DRAM-less) (rev 01)
computer.MaxiMox.NVME_1.id=123
computer.MaxiMox.NVME_1.command=sensors nvme-pci-0500
computer.MaxiMox.NVME_1.sensor=Composite:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.MaxiMox.NVME_2.id=124
computer.MaxiMox.NVME_2.command=sensors nvme-pci-0800
computer.MaxiMox.NVME_2.sensor=Composite:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.MaxiMox.NVME_3.id=125
computer.MaxiMox.NVME_3.command=sensors nvme-pci-0900
computer.MaxiMox.NVME_3.sensor=Composite:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.MaxiMox.NVME_4.id=126
computer.MaxiMox.NVME_4.command=sensors nvme-pci-0a00
computer.MaxiMox.NVME_4.sensor=Composite:[^+]*\\+(\\d+\\.\\d+)\u00b0C
computer.MaxiMox.NIC.id=127
computer.MaxiMox.NIC.command=sensors r8169_0_b00:00-mdio-0
computer.MaxiMox.NIC.sensor=temp1:[^+]*\\+(\\d+\\.\\d+)\u00b0C


